"""Map independent-plan tasks to Week2_Task_Tracker(1).xlsx rows.

Coverage:
  CLOSES  — after this plan task, the tracker A-row verification can be marked done
  PARTIAL — this plan does the no-wait slice; the tracker row stays open for design/policy
  VERIFY  — tracker already DONE; confirm in the UI only
  NEW     — not a tracker row (Yengwe TV shell)
  OUT     — tracker row exists but this plan does not work it
"""

PLAN_LABELS = {
    "T1": "malaria_risk_data SQL: stop -1",
    "T2": "woreda_region_map SQL: stop -1",
    "6.1": "Malaria charts 97–104",
    "6.2": "Maps 74, 89, 161, 58, 95",
    "6.3": "Summary KPIs 5 / 10 / 11",
    "6.4": "PHEM 152–154",
    "6.5": "Equity cards 112–118",
    "6.6": "Triangulation 216–218 / chart 27",
    "6.7": "Empty-state copy",
    "T3": "TV fit() 1:1, no scale()",
    "T4": "TV skip blank slides",
    "T5": "Hide ASK AI on TV",
    "T6": "22px off laptop theme",
}


# Columns: plan_id, plan_task, wave, tracker_task, finding, stream, severity,
# tracker_status, coverage, tracker_title, plan_does, tracker_remainder

ROWS = [
    [
        "T1",
        "malaria_risk_data SQL: stop toFloat64(-1)",
        "1",
        "F-002-A",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "The −999 to −1 band appears in map legends",
        "NULL instead of -1 on risk_index_final; keep data_status",
        "Hatched “Not reported” polygons stay out (plugin). Do not wait for them.",
    ],
    [
        "T1",
        "malaria_risk_data SQL: stop toFloat64(-1)",
        "1",
        "F-049-A",
        "F-049",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Empty-state handling is silent; Malaria −1 – −1 footnote",
        "Removes the manufactured -1 that AVG() prints as -1.0 / legend -1 – -1",
        "F-049-B empty-state component stays design. Default-filter polish is Wave 2.",
    ],
    [
        "T2",
        "woreda_region_map SQL: stop toFloat64(-1)",
        "1",
        "F-002-A",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "The −999 to −1 band appears in map legends",
        "NULL on target_achievement_pct; delete the -999…-1 legend-bucket SQL comment",
        "Hatched fill stays out. Charts 74/89/161 must also rebind (Wave 2).",
    ],
    [
        "6.1",
        "Malaria charts 97, 99, 100, 101, 102, 104",
        "2",
        "F-049-A",
        "F-049",
        "A",
        "MAJOR",
        "TODO",
        "CLOSES",
        "Set default filters on Malaria; suppress the −1 – −1 footnote",
        "Drop dead period_date filter; data_status=has_data; layer_type=woreda; 101 empty → NULL not 0",
        "F-049-B designed empty-state component remains open.",
    ],
    [
        "6.1",
        "Chart 103 Malaria Risk Distribution Heatmap",
        "2",
        "F-002-A",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "Filter −999…−1 out of every choropleth legend",
        "Filter has_data OR region; mohTvSequential; row_limit 2000; Ignore-null OFF",
        "Hatched missing polygons not in this plan.",
    ],
    [
        "6.1",
        "Chart 103 colour",
        "2",
        "F-035-A",
        "F-035",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Red/green is the primary encoding on the most prominent visuals",
        "Switch map to mohTvSequential (already registered)",
        "F-035-B palette inventory / colour-blind status tokens stay design.",
    ],
    [
        "6.2",
        "Chart 74 Institutional Maternal Deaths Heat Map",
        "2",
        "F-001-A",
        "F-001",
        "A",
        "BLOCKER",
        "TODO",
        "CLOSES",
        "Invert chart 74 ramp; add a high = bad note",
        "Metric AVG(total_value) not achievement %; mohTvSequential; legend More deaths — worse",
        "F-001-B designed choropleth rule / palette sheet stays design.",
    ],
    [
        "6.2",
        "Chart 74",
        "2",
        "F-035-A",
        "F-035",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Switch charts 161 and 74 to single-hue sequential ramps",
        "Same mohTvSequential bind as F-001-A",
        "F-035-B remains.",
    ],
    [
        "6.2",
        "Chart 74 / 89 outlines",
        "2",
        "F-002-A",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "−999 to −1 band in map legends",
        "data_status filter + Ignore-null OFF after T2",
        "Hatch plugin not in this plan.",
    ],
    [
        "6.2",
        "Chart 89 Early Neonatal Death Heatmap",
        "2",
        "F-002-A",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "Tracker links chart 89 on F-002-A",
        "mohTvSequential; has_data OR region; legend darker = worse",
        "Hatch plugin not in this plan.",
    ],
    [
        "6.2",
        "Chart 161 Woreda Level Heatmap",
        "2",
        "F-003-A",
        "F-003",
        "A",
        "BLOCKER",
        "DONE",
        "VERIFY",
        "Set row_limit ≥ 2,000 on charts 161 and 58",
        "row_limit already 2000 on 161 — leave it. Confirm no amber icon at national.",
        "None if the icon is gone. Chart 58 is still 1000 (next row).",
    ],
    [
        "6.2",
        "Chart 161 colour / legend",
        "2",
        "F-034-A",
        "F-034",
        "A",
        "MAJOR",
        "TODO",
        "CLOSES",
        "RHI heatmap legend is non-monotonic; sort bands ascending",
        "mohTvSequential is monotonic light→dark",
        "None for 161 once the scheme is selected.",
    ],
    [
        "6.2",
        "Chart 161 colour",
        "2",
        "F-035-A",
        "F-035",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Switch 161 and 74 to single-hue sequential",
        "mohTvSequential",
        "F-035-B remains.",
    ],
    [
        "6.2",
        "Chart 58 Quarterly Map row_limit",
        "2",
        "F-003-A",
        "F-003",
        "A",
        "BLOCKER",
        "DONE",
        "PARTIAL",
        "Set row_limit ≥ 2,000 on 161 and 58",
        "Tracker marked DONE but live metadata still has row_limit 1000 on 58. Raise it.",
        "Re-verify national view after save.",
    ],
    [
        "6.2",
        "Chart 95 TB heatmap row_limit + colour",
        "2",
        "F-002-A",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "F-002-A More-links include chart 95",
        "row_limit 2000; mohTvSequential",
        "Hatch plugin not in this plan.",
    ],
    [
        "6.2",
        "Chart 26 (dashboard 1 v0) optional",
        "2",
        "—",
        "F-002",
        "A",
        "BLOCKER",
        "TODO",
        "OUT",
        "Not a live dashboard-3/8 slice",
        "Skip unless someone still opens dashboard 1",
        "v0 is out of this plan.",
    ],
    [
        "6.3",
        "Chart 10 Performance >100%",
        "2",
        "F-006-A",
        "F-006",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Coverage values over 100% are unexplained",
        "Use metric “performance capped” OR Subheader footnote on denominator",
        "ⓘ tooltip + Adjusted Denominator link stays extra. F-067-A is Report Generator, not this.",
    ],
    [
        "6.3",
        "Charts 5 / 10 / 11 subheaders",
        "2",
        "F-031-A",
        "F-031",
        "A",
        "BLOCKER",
        "TODO",
        "PARTIAL",
        "No status signal on KPI cards — add vs-target variance",
        "Unit subheader; optional Markdown or fourth card AVG(target_variance_abs)",
        "F-031-B custom KPI card / RAG band stays design. Do not build Nobert/Shepherd.",
    ],
    [
        "6.3",
        "Charts 5 / 11 units",
        "2",
        "F-018-A",
        "F-018",
        "A",
        "MINOR",
        "TODO",
        "PARTIAL",
        "Summary KPI cards omit the Target value from the card face",
        "Target card already exists (11). Subheader states the unit.",
        "25 Summary thematic cards are not all in this plan — only RHI 5/10/11.",
    ],
    [
        "6.3",
        "Charts 5 / 10 / 11 subheader",
        "2",
        "F-068-A",
        "F-068",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Exported charts carry no period, geography, source",
        "Subheader can name the unit now",
        "Full period·org·source band is F-068-B context strip — blocked on design.",
    ],
    [
        "6.4",
        "Chart 152 National CFR arithmetic",
        "2",
        "F-063-B",
        "F-063",
        "B",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "PHEM exception panel + threshold banding (links 150–154)",
        "Replace SUM(cfr) with SUM(deaths)*1000/SUM(cases). No invented WHO line.",
        "Exception panel and threshold numbers stay blocked on MoH/WHO (out of this PDF).",
    ],
    [
        "6.4",
        "Chart 153 Cases by Region colour / sort",
        "2",
        "F-047-A",
        "F-047",
        "A",
        "MINOR",
        "TODO",
        "PARTIAL",
        "Bar-chart sorting not standardised; lists chart 153",
        "mohTvCategorical; sort descending if not already",
        "F-063-B threshold banding not in this plan.",
    ],
    [
        "6.4",
        "Chart 154 Deaths by Region colour",
        "2",
        "F-035-A",
        "F-035",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Red/green primary encoding",
        "mohTvSequential on the heatmap",
        "F-063-B exception panel remains.",
    ],
    [
        "6.5",
        "Equity cards 112–118 subheaders",
        "2",
        "F-073-A",
        "F-073",
        "A",
        "MAJOR",
        "TODO",
        "CLOSES",
        "Health Equity presents measures as bare numbers with no definition",
        "One-line Big Number subheader per card (definition + neutral value)",
        "F-074-A axis units and F-075-A series names are separate and not in this plan.",
    ],
    [
        "6.6",
        "Triangulation: confirm 216–218, hide 27 if present",
        "2",
        "F-004-A",
        "F-004",
        "A",
        "BLOCKER",
        "DONE",
        "VERIFY",
        "Split chart 27 into four panels",
        "Live dashboard_slices already has 216/217/218 on dashboard 3; 27 is not placed",
        "If 27 reappears on the tab, delete from layout.",
    ],
    [
        "6.7",
        "Empty-state copy (Handlebars / Big Number)",
        "2",
        "F-081-A",
        "F-081",
        "A",
        "MINOR",
        "TODO",
        "PARTIAL",
        "Empty state explains itself in database language",
        "Replace NULL / “No data after filtering…” with “No figure for this period…”",
        "F-081-B / F-049-B designed empty-state component stays design. Chart 140 is the tracker example; apply the same copy to malaria 97–101.",
    ],
    [
        "6.7",
        "Empty-state copy on malaria cards",
        "2",
        "F-049-A",
        "F-049",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Empty-state handling is silent",
        "Copy change on 97–101 after SQL/filters",
        "F-049-B remains.",
    ],
    [
        "T3",
        "TV fit(): 1920×1080, no CSS scale()",
        "3",
        "—",
        "—",
        "—",
        "—",
        "—",
        "NEW",
        "Not in Week2_Task_Tracker — Yengwe TV shell",
        "Replace fit() in moh_assets.py; letterbox on #000",
        "Do not wait for a tracker row. Add one if HABTech wants it (suggest F-TV-SCALE).",
    ],
    [
        "T4",
        "TV skip a slide that did not render",
        "3",
        "F-011-A",
        "F-011",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "PHC tab long load window indistinguishable from empty",
        "After 8s with no charts, next() — covers PHC empty chrome on the wall",
        "Laptop PHC Markdown banner is still F-011-A leftover. F-011-B skeleton is design.",
    ],
    [
        "T4",
        "TV skip blank / failed malaria extract",
        "3",
        "F-049-A",
        "F-049",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "Empty-state handling is silent",
        "Do not burn 30–45s on a blank TV slide",
        "Laptop empty-state component is F-049-B.",
    ],
    [
        "T5",
        "Hide ASK AI on /moh-static/tv only",
        "3",
        "F-043-A",
        "F-043",
        "A",
        "MINOR",
        "TODO",
        "PARTIAL",
        "Floating ASK AI button overlaps chart content",
        "CSS in TV unlockScroll() hides the launcher inside the iframe",
        "F-043-A laptop dismiss/drag stays optional. F-043-B header entry is design — out of this plan.",
    ],
    [
        "T6",
        "Do not apply 22px TV type to laptop THEME_DEFAULT",
        "3",
        "F-010-A",
        "F-010",
        "A",
        "MAJOR",
        "TODO",
        "PARTIAL",
        "HI tab bar overflows / labels truncate",
        "22px on THEME_DEFAULT inflates laptop chrome. Revert laptop to ~14px.",
        "F-010-A tab padding/order and F-010-B nav redesign are not this task.",
    ],
]

# Tracker rows this plan deliberately does not start.
OUT_OF_PLAN = [
    ["F-005-A / F-005-B", "F-005", "BLOCKER", "Freshness / as-of strip", "Needs ETL metadata + shell design"],
    ["F-031-B", "F-031", "BLOCKER", "Custom KPI card with RAG", "Nobert/Shepherd — design pack"],
    ["F-001-B", "F-001", "BLOCKER", "Designed choropleth rule sheet", "Palette.html sign-off"],
    ["F-043-B", "F-043", "MINOR", "ASK AI in portal header", "Shell design"],
    ["F-049-B", "F-049", "MAJOR", "Empty-state component", "Design"],
    ["F-063-B remainder", "F-063", "MAJOR", "PHEM thresholds + exception panel", "MoH/WHO numbers"],
    ["F-066-A", "F-066", "BLOCKER", "Report Generator period header", "Custom app code"],
    ["F-042-B", "F-042", "MINOR", "In-portal feedback", "Decision 1"],
    ["F-081-B / F-026-C", "F-081 / F-026", "MINOR / POLISH", "Amharic", "Ministry localisation"],
]
